-- CREATE TABLES --
CREATE TABLE IF NOT EXISTS db.users (uid INTEGER PRIMARY KEY AUTOINCREMENT,
  fname VARCHAR(80), lname VARCHAR(80), phone INT, email VARCHAR(80));

CREATE TABLE IF NOT EXISTS db.regions (uid INTEGER PRIMARY KEY AUTOINCREMENT,
  rname VARCHAR(80));

CREATE TABLE IF NOT EXISTS db.cities (uid INTEGER PRIMARY KEY AUTOINCREMENT,
  cname VARCHAR(80), region_id INT, FOREIGN KEY (region_id) REFERENCES regions(uid));

CREATE TABLE IF NOT EXISTS db.comments (uid INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT, user_id INT, FOREIGN KEY (user_id) REFERENCES users(uid));